import { sql } from "drizzle-orm";
import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";

import { organization, user } from "./auth";

/** Primary key: time-ordered UUID generated by Postgres 18. */
export const id = () =>
  uuid()
    .primaryKey()
    .default(sql`uuidv7()`);

/** Tenant column. Any table with it gets RLS automatically (src/db/sql/post-migrate.sql). */
export const organizationId = () =>
  uuid()
    .notNull()
    .references(() => organization.id, { onDelete: "restrict" });

/** An instant, stored as timestamptz (UTC). */
export const instant = () => timestamp({ withTimezone: true, mode: "date" });

/** Money in DZD centimes. Never a float (CLAUDE.md §7). */
export const money = () => bigint({ mode: "bigint" });

export const createdAt = () => instant().notNull().defaultNow();

export const updatedAt = () =>
  instant()
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

export const userRef = () => uuid().references(() => user.id, { onDelete: "restrict" });

/** created/updated metadata shared by business tables. */
export const timestamps = () => ({
  createdAt: createdAt(),
  updatedAt: updatedAt(),
  createdBy: userRef(),
});

/** Soft delete (business records only — never payments or receipts). */
export const softDelete = () => ({
  deletedAt: instant(),
  deletedBy: userRef(),
});
