/**
 * Post-processes the Better Auth generated schema:
 * - every `timestamp("x")` becomes `timestamp("x", { withTimezone: true })` (instants are timestamptz, CLAUDE.md §7)
 * - prepends a "generated" header.
 */
import { readFileSync, writeFileSync } from "node:fs";

const file = "src/db/schema/auth.ts";
const header =
  "// GENERATED by `pnpm auth:generate` (Better Auth CLI + scripts/auth-schema-postprocess.ts).\n" +
  "// Do not edit by hand: change src/server/auth/schema-options.ts and regenerate.\n\n";

const source = readFileSync(file, "utf8").replace(/^\/\/ GENERATED[\s\S]*?\n\n/, "");
const output = source.replace(
  /timestamp\("([a-z_]+)"\)/g,
  'timestamp("$1", { withTimezone: true })',
);

writeFileSync(file, header + output);
